### ISSUE TITLE
Deployment error running git reset --hard

### ISSUE THREAD

**Issue by bravo-kernel** [ef4/ember-cli-deploy-git#20]
Running into the following when trying to deploy using `ember deploy production`:

```
Deploying [===>----] 50% [plugin: git -> prepare]Error: git reset --hard exited with nonzero status

 at ChildProcess.<anonymous> (/home/vagrant/projects/cell-deploy/node_modules/ember-cli-deploy-git/lib/run.js:19:19)

Error: git reset --hard exited with nonzero status
  at emitTwo (events.js:126:13)
  at ChildProcess.emit (events.js:214:7)
  at maybeClose (internal/child_process.js:925:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Pipeline aborted
```

**Comment by bravo-kernel** [comment]
Solution:

> unless you’ve configured it differently, you should have a folder called `deploy-<project-name>` as a sibling to your `<project-name>` directory that you’re running `ember deploy` in

Delete that sibling directory and re-run.
