### ISSUE TITLE
Error on deploy: 'gh-pages' is already checked out 

### ISSUE THREAD

**Issue by ninjatronic** [ef4/ember-cli-deploy-git#27]
I followed the setup instructions to the letter. When I try to deploy I receive this error...
```
λ ember deploy production
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: covid-azores -> ember-cli-deploy-github-pages -> ember-cli-babel
Deploying [>------] 14% [plugin: github-pages -> willDeploy]DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: C:\Users\Pete\dev\covid-azores\node_modules\ember-cli-deploy-github-pages\node_modules\ember-cli-babel
WARNING: You have not included `ember-cli-shims` in your project's `bower.json` or `package.json`. This only works if you provide an alternative yourself and unset `app.vendorFiles['app-shims.js']`.
WARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.
cleaning up...
Deploying [==>----] 43% [plugin: git -> prepare]fatal: 'gh-pages' is already checked out at 'C:/Users/Pete/dev/deploy-covid-azores'
Error: Command failed: git checkout  gh-pages
fatal: 'gh-pages' is already checked out at 'C:/Users/Pete/dev/deploy-covid-azores'

Error: Command failed: git checkout  gh-pages
fatal: 'gh-pages' is already checked out at 'C:/Users/Pete/dev/deploy-covid-azores'

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Command.execSync (C:\Users\Pete\dev\covid-azores\node_modules\gitty\lib\command.js:52:10)
    at Repository.checkoutSync (C:\Users\Pete\dev\covid-azores\node_modules\gitty\lib\repository.js:432:7)
    at Class.prepare (C:\Users\Pete\dev\covid-azores\node_modules\ember-cli-deploy-github-pages\index.js:72:14)
    at Object.fn (C:\Users\Pete\dev\covid-azores\node_modules\ember-cli-deploy\lib\tasks\pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (C:\Users\Pete\dev\covid-azores\node_modules\ember-cli-deploy\lib\models\pipeline.js:173:19)
    at tryCatch (C:\Users\Pete\dev\covid-azores\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\Users\Pete\dev\covid-azores\node_modules\rsvp\dist\rsvp.js:538:13)
    at publish (C:\Users\Pete\dev\covid-azores\node_modules\rsvp\dist\rsvp.js:508:7)
    at flush (C:\Users\Pete\dev\covid-azores\node_modules\rsvp\dist\rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)Pipeline aborted
```

**Comment by ef4** [comment]
Hi, thanks for reporting.

ember-cli-deploy-git uses git worktrees, and you can only have one git worktree per branch. The error says that you already have one at C:/Users/Pete/dev/deploy-covid-azores, so it must be trying to make a new one somewhere else.

Did you customize `worktreePath`? If so, delete the one in deploy-covid-azores first, and use `git worktree prune` to make sure git knows its gone.
